using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hypercube.Analyzers.Generators;

[Generator]
public sealed class IdStructGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not SyntaxReceiver receiver) 
            return;

        foreach (var structDecl in receiver.CandidateStructs)
        {
            var model = context.Compilation.GetSemanticModel(structDecl.SyntaxTree);
            var symbol = ModelExtensions.GetDeclaredSymbol(model, structDecl);
            if (symbol is null)
                continue;
            
            var attribute = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "IdStructAttribute");
            if (attribute is null)
                continue;

            var underlyingType = attribute.ConstructorArguments[0].Value as INamedTypeSymbol;
            var typeName = underlyingType?.ToDisplayString() ?? "int";
            
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            var structName = symbol.Name;

            var source = $$"""
                           // <auto-generated/>
                           #nullable enable

                           using System;
                           using System.Diagnostics;
                           using System.Runtime.CompilerServices;
                           using System.Runtime.InteropServices;

                           namespace {{namespaceName}}
                           {
                               [DebuggerDisplay("{Value}")]
                               [StructLayout(LayoutKind.Sequential)]
                               public readonly partial struct {{structName}} : IEquatable<{{structName}}>
                               {
                                   public readonly {{typeName}} Value;

                                   public {{structName}}({{typeName}} value) => Value = value;
                                   
                                   public override string ToString() => Value.ToString();

                                   [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                   public bool Equals({{structName}} other) => Value == other.Value;

                                   [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                   public override bool Equals(object? obj) => obj is {{structName}} id && Equals(id);

                                   [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                   {{GenerateHashCodeMethod(typeName)}}

                                   [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                   public static implicit operator {{typeName}}({{structName}} id) => id.Value;

                                   [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                   public static implicit operator {{structName}}({{typeName}} value) => new {{structName}}(value);

                                   [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                   public static bool operator ==({{structName}} a, {{structName}} b) => a.Value == b.Value;

                                   [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                   public static bool operator !=({{structName}} a, {{structName}} b) => a.Value != b.Value;
                               }
                           }

                           """;

            context.AddSource($"{structName}_IdBindings.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateHashCodeMethod(string typeName)
    {
        return typeName == "int" ? "public override int GetHashCode() => Value;" : "public override int GetHashCode() => Value.GetHashCode();";
    }

    private class SyntaxReceiver : ISyntaxReceiver
    {
        public List<StructDeclarationSyntax> CandidateStructs { get; } = [];

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is StructDeclarationSyntax structDecl && structDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                CandidateStructs.Add(structDecl);
            }
        }
    }
}